apiVersion: v2
name: envoy-sidecar-demo
description: Envoy Proxy를 Sidecar로 붙인 데모 테스트 Helm 차트
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - envoy
  - sidecar
  - proxy
  - demo
maintainers:
  - name: nhn
