apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: rook-ceph-store
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPool:
    replicated:
      size: 3
  gateway:
    instances: 1
    port: 80
