apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-sidecar-demo.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "envoy-sidecar-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "envoy-sidecar-demo.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http-envoy
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePortHttp }}
      nodePort: {{ .Values.service.nodePortHttp }}
      {{- end }}
    - name: envoy-admin
      port: {{ .Values.service.adminPort }}
      targetPort: envoy-admin
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePortAdmin }}
      nodePort: {{ .Values.service.nodePortAdmin }}
      {{- end }}
